FROM openjdk:21-jdk-bookworm

# Install SoftHSM2, OpenSC (pkcs11-tool) openssl PKCS#11 integration and related tools
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential git autoconf automake libtool pkg-config \
    libpcsclite-dev libssl-dev pcscd \
    curl ca-certificates \
    softhsm2 libsofthsm2 libengine-pkcs11-openssl \
 && rm -rf /var/lib/apt/lists/*

# build OpenSC 0.26.1
WORKDIR /tmp
RUN curl -L -o opensc-0.26.1.tar.gz https://github.com/OpenSC/OpenSC/releases/download/0.26.1/opensc-0.26.1.tar.gz \
 && tar xzf opensc-0.26.1.tar.gz \
 && cd opensc-0.26.1 \
 && ./configure --prefix=/usr --disable-static --without-cmocka \
 && make -j"$(nproc)" \
 && make install \
 && ldconfig
# Install Mastercard pkcs11-tools
RUN curl -L -o /tmp/pkcs11-tools.tar.gz \
       https://github.com/Mastercard/pkcs11-tools/releases/download/v2.6.0/pkcs11-tools-2.6.0.tar.gz \
 && tar xzf pkcs11-tools.tar.gz && cd pkcs11-tools-2.6.0 \
 && ./configure --prefix=/usr \
 && make -j"$(nproc)" \
 && make install && cd /
# Reset work dir to root
WORKDIR /

# Copy setup and configuratioin resources
COPY src/main/resources/dev/kek.bin /opt/kek.bin
COPY src/main/resources/dev/softhsm2.conf /opt/softhsm2.conf
COPY src/main/resources/dev/softhsm2-p256.conf /opt/softhsm2-p256.conf
COPY src/main/resources/dev/softhsm2-p384.conf /opt/softhsm2-p384.conf
COPY src/main/resources/dev/softhsm2-p521.conf /opt/softhsm2-p521.conf
COPY src/main/resources/dev/p11-keygen.sh /p11-keygen.sh
RUN chmod +x /p11-keygen.sh

# Set environment variables
ENV SOFTHSM2_CONF=/opt/softhsm2.conf
ENV PKCS11LIB=/usr/lib/softhsm/libsofthsm2.so
ENV PKCS11PASSWORD=123456
ENV PKCS11SLOT=0
# Key gen script ENV
ENV PKCS11_MODULE=$PKCS11LIB
ENV LIBPKCS11=/usr/lib/aarch64-linux-gnu/engines-3/libpkcs11.so

# Init SoftHSM2
RUN softhsm2-util --init-token --slot 0 --label "wallet-keys" \
      --so-pin "1938456231" --pin "123456"

# Import static KEK key to retain keys after image rebuild to match existing key records
RUN pkcs11-tool --module "$PKCS11LIB" \
  --slot-index "$PKCS11SLOT" --login --pin "$PKCS11PASSWORD" \
  --write-object /opt/kek.bin \
  --type secrkey \
  --key-type AES:32 \
  --label kek-1 --id 01 \
  --usage-decrypt --usage-wrap

# Replace with this to generate a random KEK key inside the HSM - Using this option is not compatible with storing and reusing wrapped keys after image rebuild.
#RUN pkcs11-tool --module $PKCS11LIB \
#    --slot-index $PKCS11SLOT --login --pin $PKCS11PASSWORD \
#    --keygen --key-type AES:32 \
#    --label kek-1 --id 01

# Copy application config and app
COPY src/main/resources/application-hsm.yml /config/application-hsm.yml
COPY src/main/resources/application-demo.yml /config/application-demo.yml
COPY target/remote-hsm-hsmserver-*.jar /app.jar
# Copy demo data
COPY target/test-classes /target/test-classes

EXPOSE 8080

ENTRYPOINT ["java","-XX:UseSVE=0", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000","-jar","/app.jar"]
